name: trive

layers:
  base:
    from: hypothesis/base
    context:
      - requirements.txt
  app:
    context:
      - .
    build:
      - cd /
      - ls
      - ls /app
      - ls /var/lib/hypothesis
      - rm -rf /var/lib/hypothesis
      - mv /app /var/lib/hypothesis
      - cd /var/lib/hypothesis
      - pip install --no-cache-dir -r requirements.txt
      - ls
      - ls /var/lib/hypothesis/
      - sh /var/lib/hypothesis/build_gulp.sh
    prepare: ls
    start: init-env supervisord -c conf/supervisord.conf
    wait-for: db:5432
  test:
    build:
      - pip install tox
    start: tox
    wait-for: db:5432

build:
  branches:
    - master
