version: "2"
services:
  test:
    build: .
    depends_on:
      - postgres
      - elasticsearch
      - rabbit
  postgres:
    image: postgres:9.4-alpine
  elasticsearch:
    image: nickstenning/elasticsearch-icu
  rabbit:
    image: rabbitmq:3.6-management-alpine
